### PR TITLE
fix multiple execution times - fixes #21

### LINKED ISSUE #21: applyEditorConfigToTextEditor is executed multiple times
When debugging this plugin, I noticed that the [applyEditorConfigToTextEditor](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L90-L118) method is executed multiple times. These are my findings.

When switching to another file, the method is always executed two times. The first time the `textEditor` is pointing to the file being closed, the second time it is pointing to the file being opened. The reason for this is that the [`onDidChangeActiveTextEditor`](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L11-L13) event is fired and the [`onDidOpenTextDocument`](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L37).

When opening a new window where a file is already active, the method even executes 3 times. The first 2 times are caused by the two blocks I pointed to above, the third time is caused because of the [`rebuildConfigMap`](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L52).

Any feedback on this?

### PR DESCRIPTION
**Pull request by SamVerschueren**
This PR fixes #21. By only using one event instead of 2, it makes sure the `applyEditorConfigToTextEditor` is only executed once.

I'm really not familiar with testing extension in VS Code, I can look in that if I find more time. In the mean time, feel free to provide feedback, improvements, ...

### CODE REVIEW

**Comment by jednano** [comment]
@SamVerschueren this has been published in a forked [`EditorConfig`](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) extension as [v0.2.0](https://github.com/editorconfig/editorconfig-vscode/blob/master/CHANGELOG.md#020).

**Comment by SamVerschueren** [comment]
Might have to test that this works in all use cases. Will install your plugin to see if it behaves correctly :).

**Comment by jednano** [comment]
@SamVerschueren by all means. I wanted to move this along and start using the extension until problems arise, because the project isn't exactly tested properly and probably never will be (extensions are super hard to test properly w/o BDD). That makes us, the humans, responsible for real-world testing and that's why the version number is still a pre-release. Definitely more things to iron out, but I think we can iterate faster this way.

Also, there are still some vscode features that are not exposed to extension developers, preventing us from implementing the remaining EditorConfig rules on this extension, so we're waiting for that, of course.

**Comment by jednano** [comment]
@SamVerschueren BTW – I have a little EditorConfig playground on my hard drive that I use to play around with settings as they change between files and I experienced no issues whatsoever with your changes. In fact, it fixed issues I was having with the extension previously, so I think we're in a good place.

**Comment by SamVerschueren** [comment]
@jedmao You should open the issue tracker on the fork as it is going to live it's own life :).

**Comment by jednano** [comment]
@SamVerschueren good call! I didn't realize the issue tracker was off.

**Comment by chrisdias** [comment]
@SamVerschueren I'm not sure why the MSBOT just responded now :).  i'm going to close this PR given that this repository is no longer active.

**Comment by SamVerschueren** [comment]
I signed the CLA for a PR in the VS Code repository. So although I didn't have to sign it for this one, it seems that he still responded :).

**Pull request closed without merging**
