### PR TITLE
fix texteditor defaults - fixes #19

### LINKED ISSUE #19: tab_size is sometimes set wrong
This is my `.editorconfig`

```
root = true

[*]
indent_style = tab
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[{package.json,*.yml}]
indent_style = space
indent_size = 2

[*.md]
trim_trailing_whitespace = false
```

It has some properties that are not yet supported, but it's future proof :).

One thing I noticed is that the `tab_size` is sometimes calculated wrong. My `editor.tabSize` setting is set to `auto`. But when set to `4`, the issue remains. So I use tabs on all my files, except in `package.json` and in all the `.yml` files.

The most basic project structure looks something like this

```
/
 |- package.json
 |- index.js
 |- .editorconfig
```

#### Steps to reproduce

1. Open the project directory
2. Open `index.js
  * The plugin indicates `EditorConfig: Tabs: 4`
3. Open `package.json`
  * The plugin indicates `EditorConfig: Spaces: 2`
4. Open `index.js`
  * The plugin indicates `EditorConfig: Tabs: 2`

As you can see, after opening a file with spaces (2), the `tab_size` is using not being reset to the correct value because my `.editorconfig` file is not specifying the `indent_size` when using tabs.

### PR DESCRIPTION
**Pull request by SamVerschueren**
This PR fixes #19 

Not sure if this is the best way of doing it (fairly new to the codebase). So any suggestions are more then welcome.

### CODE REVIEW

**Comment by jednano** [comment]
:+1: this looks good to me. If I understand correctly, you're saving the defaults and restoring those defaults between file switches. I did something similar on the Visual Studio plugin and I definitely support this method.

My only concern is this – what happens when someone changes their defaults? Do they have to restart Visual Studio Code or is there a way to respond to that as well? Maybe that's for another PR though.

**Comment by SamVerschueren** [comment]
> My only concern is this – what happens when someone changes their defaults?

Good point! If I'm not mistaken, we can attach a listener that listens for changes in the settings, if that happens, we have to update our defaults to the defaults of the settings. Actually, it might be better to create a method `retrieveDefaults` or something like that, and call that the first time the plugin runs. When the settings change, call the `retrieveDefaults` again and overwrite the defaults object.

I think it fits in this PR as the current behaviour adapts to changes in the settings. By merging this, that behaviour breaks. Will update my PR (hopefully somewhere today).

**Comment by jednano** [comment]
Everything you said sounds like the perfect way to do it. I look forward to seeing it in this PR.

**Comment by SamVerschueren** [comment]
Alright, after trying that and looking at the API docs, I don't think we can solve this at the moment. Here's why.

Yes you can retrieve the settings of the user, no problem with that one

``` js
const config: WorkspaceConfiguration = workspace.getConfiguration('editor');
```

But the result is a `WorkspaceConfiguration` object which could hold the value `auto` for `insertSpaces` and `tabSize`. If that is the case, the editor will guess those values based on the file being opened. I don't think it's a good idea to try to mimic that behaviour if VS Code is already doing that under the hood. So retrieving the workspace configuration isn't really an option (unless the user has set fixed values).

So I tried to dig more into the behaviour and attached the following event

``` js
window.onDidChangeTextEditorOptions((e: TextEditorOptionsChangeEvent) => {
    // e.options is the textEditor.options object
});
```

I disabled the `applyEditorConfigToTextEditor` and put a breakpoint on that event. If my configuration settings are set to `auto` and I switch from a file using tabs, to a file using spaces, the event is triggered. Because in the background, VS Code detects that the new file is using spaces and it updates the `options` object of the text editor. If I switch back to a file with tabs, the event is fired again. If I then switch to a file that's using tabs as well, the event is not triggered because the options didn't have to change.

So I thought, what if I store the options passed in with the event and store that as `defaults` object. It would make sense, because if you switch a file that's using spaces, the event is triggered, the defaults are being updated to the defaults of the current file. But there is just one thing going wrong for this approach. And that is the event fired at [line 37](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L37) (onDidOpenTextDocument) is fired before the `onDidChangeTextEditorOptions` event. Which means, the new editor config options are applied with the wrong set of defaults.

I think in order to solve this problem, we need some extra internal information that is currently not exposed by the API. Maybe the applied text editor options should be decoupled from the options set by VS Code itself. That way, you can always access the default settings of the file. But in order to help us out on this, we need some feedback from @chrisdias @egamma 

Can always create a new issue in the VS Code repo.

**Comment by jednano** [comment]
I thought we were doing away with `onDidOpenTextDocument` and just using `onDidChangeTextEditorOptions` to prevent the double fire?

Aside from that, we have to accept the possibility that the EditorConfig configuration for a particular file doesn't even have an indentation setting, in which case, it would just fallback to the default VSCode user setting, which may well be `auto`, so I don't think it's useless. EditorConfig only does the override to `auto` if the configuration has indentation settings (i.e., `indent_style` and `indent_size`).

I think I saw something in this plugin that has like a 4-space default? I definitely don't think we should be doing that, especially if we have a fallback to user defaults.

Does that help at all? Your investigation here is extremely thorough and I appreciate all your hard work.

**Comment by SamVerschueren** [comment]
>  thought we were doing away with `onDidOpenTextDocument` and just using `onDidChangeTextEditorOptions` to prevent the double fire?

Yes, it's not as simple as just removing `onDidOpenTextDocument`. Needs some refactoring but yes it seems to work. But the `onDidChangeActiveTextEditor` event is fired before `onDidChangeTextEditorOptions` which makes it we can't detect the defaults generated by VS Code for that specific file when `tabSize` or `insertSpaces` is set to `auto` in the settings file.

> Aside from that, we have to accept the possibility that the EditorConfig configuration for a particular file doesn't even have an indentation setting, in which case, it would just fallback to the default VSCode user setting, which may well be auto.

If `indent_size` is not set for a particular file, it will adapt the `indent_size` of the previously opened file which might be wrong. That's where this PR is all about :). If I open my `package.json` which has explicitely defined the `indent_size` to `2`, and then I open `index.js` which doesn't have an `indent_size` specified, it will take the current `tabSize` from the texteditor which is `2` (the one from `pakcage.json`). That behaviour isn't correct because if it's not explicitely defined. If that is the cdase, it should use the VS Code settings to detect the `tabSize` but that isn't possible if `tabSize` is set to `auto`.

> I think I saw something in this plugin that has like a 4-space default?

You probably mean this block

``` ts
public static resolveTabSize(tabSize: number|string) {
    return (tabSize === 'auto') ? 4 : parseInt(tabSize + '', 10);
}
```

It's only used for generating a `.editorconfig` file, so it has nothing to do with applying styles.

> Your investigation here is extremely thorough and I appreciate all your hard work.

Happy to help out :)

I know it's a lot of information, if you want me to clarify with some examples, don't hesitate to ask :).

**Comment by jednano** [comment]
@SamVerschueren this has been published in a forked [`EditorConfig`](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) extension as [v0.2.0](https://github.com/editorconfig/editorconfig-vscode/blob/master/CHANGELOG.md#020).

**Comment by jednano** [comment]
Feel free to submit more issues/PRs to [`editorconfig/editorconfig-vscode`](https://github.com/editorconfig/editorconfig-vscode). We should be able to move along faster, as I plan to support this for the foreseeable future. This repo wasn't getting support fast enough, so that's why I forked it.

**Comment by SamVerschueren** [comment]
@jedmao Cool! Will probably have to create some issues in the VSCode repository. We need some extra stuff in order to be able to support full editorconfig settings.

**Comment by jednano** [comment]
@SamVerschueren I'll be following everything very closely, so don't you worry.

**Comment by SamVerschueren** [comment]
This does not entirely fix #19. A correct implementation is implemented in https://github.com/editorconfig/editorconfig-vscode. Closing this one.

**Pull request closed without merging**
